### ISSUE TITLE
Add HIBP Breaches?

### ISSUE THREAD

**Issue by dominikheinz** [mamatb/OneWordlistToListThemAll#1]
Hey,
I think it would be a nice addition to expand this list with the data found in the HIBP breaches.
On hashes.org you can find the HaveIBeenPwnedV1 - V6 (~45GB without cleaning, deduping).
After cleaning  & deduping its probably only a couple of GB. These breaches were pretty famous in the public media, so I think they would make a good addition for this list.

**Comment by mamatb** [comment]
Hi there,
HIBP leaks V1 - V6 have just been added, ~7 GB worth of unique passwords of which ~1 GB were not yet included in OneWordlistToListThemAll. Thanks for the suggestion!
