### ISSUE TITLE
Upload the wordlist also somewhere else

### ISSUE THREAD

**Issue by Mek7** [mamatb/OneWordlistToListThemAll#2]
Hello,
the wordlist is currently on mega.co.nz that says the file is too big and requires me to pay, otherwise the transfer may be interrupted.
It would be good to have the file also on other (free) sites, or maybe split it to smaller archives.

**Comment by mamatb** [comment]
Hi there,
Originally I intended to upload the wordlist using a free service such as sql.gg, but all my tries to do so got stuck halfway through. Just tried again years later and anonfiles.com worked :)
