### ISSUE TITLE
Sort the wordlist to get hits quicker

### ISSUE THREAD

**Issue by Mek7** [mamatb/OneWordlistToListThemAll#4]
Hi,
current order of the words in the big wordlist is by starting with numbers, then uppercase characters, then lowercase characters.
To get hits quicker, especially on slower hashes, it would make more sense to order the wordlist in the order of hit probability, such as words containing:
- numbers only
- lowercase only
- lowercase + numbers
- starting with uppercase, other characters lowercase
- starting with uppercase, other characters lowercase + numbers
- then all other words...

I'm not sure how laborious would be to do it this way. Maybe there is a program that allows defining the order such as this?

**Comment by nicovell3** [comment]
Hello! You can do that with your own criteria with grep and cat. For example, for the order you proposed, you could you these commands:

```
grep -E '^[0-9]+$' passwordsFile > numbers
grep -E '^[a-z]+$' passwordsFile > lowercase
grep -Ev '^[0-9]+$' passwordsFile | grep -Ev '^[a-z]+$' | grep -E '^[0-9a-z]+$' > lowercaseAndNumbers
grep -E '^[A-Z][a-z]+$' passwordsFile > startUppercase
grep -E '^[A-Z][a-z0-9]+$' passwordsFile > startUppercaseOthers
grep -Ev '^[0-9]+$' passwordsFile | grep -Ev '^[a-z]+$' | grep -Ev '^[0-9a-z]+$' | grep -Ev '^[A-Z][a-z]+$' | grep -Ev '^[A-Z][a-z0-9]+$' > others
cat numbers lowercase lowercaseAndNumbers startUppercase startUppercaseOthers others > sortedPasswordsFile
```

I've tested them with a little file, but I suppose they will work with a big file if your machine has enough resources

**Comment by Mek7** [comment]
> Hello! You can do that with your own criteria with grep and cat. For example, for the order you proposed, you could you these commands:
> 
> ```
> grep -E '^[0-9]+$' passwordsFile > numbers
> grep -E '^[a-z]+$' passwordsFile > lowercase
> grep -Ev '^[0-9]+$' passwordsFile | grep -Ev '^[a-z]+$' | grep -E '^[0-9a-z]+$' > lowercaseAndNumbers
> grep -E '^[A-Z][a-z]+$' passwordsFile > startUppercase
> grep -E '^[A-Z][a-z0-9]+$' passwordsFile > startUppercaseOthers
> grep -Ev '^[0-9]+$' passwordsFile | grep -Ev '^[a-z]+$' | grep -Ev '^[0-9a-z]+$' | grep -Ev '^[A-Z][a-z]+$' | grep -Ev '^[A-Z][a-z0-9]+$' > others
> cat numbers lowercase lowercaseAndNumbers startUppercase startUppercaseOthers others > sortedPasswordsFile
> ```
> 
> I've tested them with a little file, but I suppose they will work with a big file if your machine has enough resources

Thank you, will try it :)

**Comment by mamatb** [comment]
Hi there,
Current order comes from the wordlist being version-sorted to remove duplicates (see [How?](https://github.com/mamatb/OneWordlistToListThemAll#how) section of the README.md file).

As @nicovell3 stated, every user can customize it based on hashrate, password policies, etc. Be aware of the size though, sorting tools will most likely need to create temp files (unless you have +100 GB of RAM) and you can run out of disk space in the process (for instance I use `sort -T` when sorting OneWordlistToListThemAll.txt to avoid filling the disk partition containing `/tmp`).
