### ISSUE TITLE
WPA PSK archives not found on anonfiles.com

### ISSUE THREAD

**Issue by vigoroous** [mamatb/OneWordlistToListThemAll#5]
Current links forward to not found page:
https://anonfiles.com/lcZcg6hbz4/OneWordlistToListThemAll_WPA_PSK_7z_001
https://anonfiles.com/9dNeg3hfz9/OneWordlistToListThemAll_WPA_PSK_7z_002

**Comment by mamatb** [comment]
Thanks for the heads up, both links have been fixed.
