### ISSUE TITLE
Clarification needed

### ISSUE THREAD

**Issue by dennis777** [mamatb/OneWordlistToListThemAll#6]
Good day,

How did you get the lists to 100GB when the lists alone are like 250GB+?

All those wordlists that you posted went through your 6 step process and then you merged it all into 1? Just seems weird that there would be 150GB+ of duplicates. I just want to make sure I understand your wordlist properly, this is aiming to be a one stop shop for all of those lists into 1 unique sorted and <32 chars list correct? 

Thank you for clarification

**Comment by dennis777** [comment]
I would also like to add the links are unfortunately dead :/

**Comment by mamatb** [comment]
Hi there,

That's correct, OneWordlistToListThemAll is a mix of all the mentioned wordlists. There were 150+ GB of duplicates, entries with non-ascii or non-visible characters, and entries longer than 32 characters. 

Regarding the dead links:
- Adeptus Mechanicus: I'm aware of the website [adeptus-mechanicus.com](https://www.adeptus-mechanicus.com/codex/hashpass/) disabling directory listing long ago, but wordlists are still there (see [eharmony.dic.7z](https://www.adeptus-mechanicus.com/codex/hashpass/eharmony.dic.7z) for example). Very few can also be found in [this repo](https://github.com/AdeptusM/hashes).
- Breach Compilation, Have I Been Pwned: can't help you with these two, not sure where can the original wordlists be found right now. Feel free to download my filtered version from Anonym File: [Breach Compilation](https://anonymfile.com/R45W/breach-compilation-unixgraph32maxsort.7z), [Have I Been Pwned](https://anonymfile.com/PrWE/hibp-unix-graph32maxsort.7z).
- OneWordlistToListThemAll, OneWordlistToListThemAll WPA-PSK: looks like AnonFiles shutted down, just updated the repo with new links to Anonym File. Thanks for the heads up.
