### ISSUE TITLE
AnonymFile link (is?) broken.

### ISSUE THREAD

**Issue by frietvet600** [mamatb/OneWordlistToListThemAll#7]
![error](https://github.com/mamatb/OneWordlistToListThemAll/assets/75941569/3d1f39e6-84dd-45d1-a8ff-92ed902a63fd)

It seems like the link is broken, I am not sure if this is an issue on my end or a general issue.

**Comment by mamatb** [comment]
Hi there,

Looks like all my files were removed from Anonym File, just updated the repo with new links to Gofile. Thanks for the heads up.
